version: "3.7"
services:
  gerador-ren-app:
    image: ghcr.io/cognicaoonline/gerador-doc:latest
    
    networks:
      - connect-stock

    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.http.routers.gerador_ren.rule=Host(`gerador-doc.cognicao.online`)
        - traefik.http.routers.gerador_ren.entrypoints=websecure
        - traefik.http.routers.gerador_ren.tls=true
        - traefik.http.routers.gerador_ren.service=gerador_ren
        - traefik.http.routers.gerador_ren.tls.certresolver=letsencryptresolver
        - traefik.http.services.gerador_ren.loadbalancer.server.port=3000

networks:
  connect-stock:
    external: true
    attachable: true
    name: connect-stock
